version: "3"
services:
  go:
    image: go
    container_name: go
    build:
      context: ./
      args:
        GO_VERSION: golang:${GO_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        TZ: ${TIMEZONE}
        GOPROXY: ${GO_PROXY}
        GO111MODULE: ${GO_111MODULE}
    ports:
      - ${GO_HOST_PORT}:${GO_HOST_PORT_I}
    privileged: true
    restart: always
    tty: true
    volumes:
      - ${SOURCE_DIR}:/go/src:rw
      - ${GO_PKG_DIR}:/go/pkg:rw
      - ${GO_BIN_DIR}:/go/bin:rw
    networks:
      - docker-network
    cap_add:
      - SYS_PTRACE
networks:
    docker-network:
        external: true