version: "3"
services:
    mongo:
        image: mongo:${MONGO_VERSION}
        privileged: true
        restart: always
        container_name: mongo
        environment:
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
          TZ: ${TIMEZONE}
        ports:
            - ${MONGO_HOST_PORT}:27017
        volumes:
            - ${MONGO_DATA_DIR}:/data/db:rw
        networks:
            - docker-network
networks:
    docker-network:
        external: true