version: "3"
services:
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    privileged: true
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=${PHPMYADMIN_HOSTS}
      - PMA_ARBITRARY=1
    ports:
      - ${PHPMYADMIN_HOST_PORT}:80
    volumes:
      - ${PHPMYADMIN_CONF_DIR}/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini   
      - ${PHPMYADMIN_CONF_DIR}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - docker-network

networks:
    docker-network:
        external: true