version: "3"
services:
    elasticsearch:
      image: elasticsearch:8.6.2
      privileged: true
      restart: always
      container_name: elasticsearch
      environment:
        - ELASTIC_PASSWORD=shizenghua
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 指定内存限制
        - "discovery.type=single-node"	# 指定单节点模式
      ports:
        - 59200:9200
        - 59300:9300
      volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data/
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins/
      networks:
        - docker-network
    kibana:
      image: kibana:8.6.2
      privileged: true
      restart: always
      container_name: kibana
      environment:
        ES_JAVA_OPTS: -Xms512m -Xmx512m
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        # ELASTICSEARCH_USERNAME: admin
        # ELASTICSEARCH_PASSWORD: shizenghua
      ports:
        - 55601:5601
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        - ./kibana/data:/usr/share/kibana/data
      networks:
        - docker-network
      depends_on:
        - elasticsearch
networks:
    docker-network:
        external: true