version: "3"
services:
    elasticsearch:
      image: elasticsearch:${ELASTIC_VERSION}
      privileged: true
      restart: always
      container_name: elasticsearch
      environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 指定内存限制
        - "discovery.type=single-node"	# 指定单节点模式
      ports:
        - ${ELASTIC_PORT}:9200
      volumes:
        - ${ELASTIC_DATA_DIR}:/usr/share/elasticsearch/data/
        - ${ELASTIC_CONF_FILE}:/usr/share/elasticsearch/config/elasticsearch.yml
        - ${ELASTIC_DATA_PLUGINS_DIR}:/usr/share/elasticsearch/plugins/
      networks:
        - docker-network
    kibana:
      image: kibana:${KIBANA_VERSION}
      privileged: true
      restart: always
      container_name: kibana
      environment:
        ES_JAVA_OPTS: -Xms512m -Xmx512m
        ELASTICSEARCH_HOSTS: ${KIBANA_ELASTICSEARCH_HOSTS}
        # ELASTICSEARCH_USERNAME: admin
        # ELASTICSEARCH_PASSWORD: shizenghua
      ports:
        - ${KIBANA_PORT}:5601
      volumes:
        - ${KIBANA_CONF_FILE}:/usr/share/kibana/config/kibana.yml
        - ${KIBANA_DATA_DIR}:/usr/share/kibana/data
      networks:
        - docker-network
      depends_on:
        - elasticsearch
networks:
    docker-network:
        external: true