version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        TZ: ${TIMEZONE}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTP_HOST_PORT_74}:8074"
      - "${NGINX_HTTP_HOST_PORT_80}:8080"
      - "${NGINX_HTTP_HOST_PORT_81}:8081"
      - "${NGINX_HTTP_HOST_PORT_82}:8082"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    restart: always
    tty: true
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_PHP_CONF_DIR}:/etc/nginx/php:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    networks:
      - docker-network
networks:
    docker-network:
        external: true