version: "3"
services:
  node14:
    image: node14
    container_name: node14
    build:
      context: ./
      args:
        NODE_VERSION: node:${NODE14_VERSION}-alpine3.17
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        TZ: ${TIMEZONE}
    ports:
      - ${NODE14_HOST_PORT}:3000
    privileged: true
    restart: always
    tty: true
    volumes:
      - ${SOURCE_DIR}:/www/:rw
    networks:
      - docker-network
    cap_add:
      - SYS_PTRACE
networks:
    docker-network:
        external: true