version: '3'
services:
  php82:
    image: php82
    container_name: php82
    restart: always
    networks:
      - docker-network
    build:
      context: ./build/
      dockerfile: ./php82/Dockerfile
      args:
        PHP_VERSION: php:${PHP82_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP82_EXTENSIONS}
        TZ: ${TIMEZONE}
    volumes:
    - ${SOURCE_DIR}:/www/:rw
    - ${PHP82_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    - ${PHP82_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    - ${PHP82_LOG_DIR}:/var/log/php
    - ${PHP82_COMPOSER_DIR}:/tmp/composer
    ports:
      - ${PHP82_PORT}:${PHP82_PORT_I}
    cap_add:
      - SYS_PTRACE
networks:
  docker-network:
    external: true