version: '3'
services:
  php80:
    image: php80
    container_name: php80
    restart: always
    networks:
      - docker-network
    build:
      context: ./build/
      dockerfile: ./php80/Dockerfile
      args:
        PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP80_EXTENSIONS}
        TZ: ${TIMEZONE}
    volumes:
    - ${PHP80_SSH_DIR}:/root/.ssh
    - ${SOURCE_DIR}:/www/:rw
    - ${PHP80_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    - ${PHP80_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    - ${PHP80_LOG_DIR}:/var/log/php
    - ${PHP80_COMPOSER_DIR}:/tmp/composer
    ports:
      - 9800:9000
    cap_add:
      - SYS_PTRACE
networks:
  docker-network:
    external: true