version: '3'
services:
  php74:
    image: php74
    container_name: php74
    restart: always
    networks:
      - docker-network
    build:
      context: ./build/
      dockerfile: ./php74/Dockerfile
      args:
        PHP_VERSION: php:${PHP74_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP74_EXTENSIONS}
        TZ: ${TIMEZONE}
    volumes:
    - ${PHP74_SSH_DIR}:/root/.ssh
    - ${SOURCE_DIR}:/www/:rw
    - ${PHP74_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    - ${PHP74_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    - ${PHP74_LOG_DIR}:/var/log/php
    - ${PHP74_COMPOSER_DIR}:/tmp/composer
    ports:
      - 9740:9000
      - 59501:59501
      - 59601:59601
    cap_add:
      - SYS_PTRACE
networks:
  docker-network:
    external: true