version: '3'
services:
  php81:
    image: php81
    container_name: php81
    restart: always
    networks:
      - docker-network
    build:
      context: ./build/
      dockerfile: ./php81/Dockerfile
      args:
        PHP_VERSION: php:${PHP81_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP81_EXTENSIONS}
        TZ: ${TIMEZONE}
    volumes:
    - ${PHP81_SSH_DIR}:/root/.ssh
    - ${SOURCE_DIR}:/www/:rw
    - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
    - ${PHP81_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    - ${PHP81_LOG_DIR}:/var/log/php
    - ${PHP81_COMPOSER_DIR}:/tmp/composer
    ports:
      - 9810:9000
    cap_add:
      - SYS_PTRACE
networks:
  docker-network:
    external: true